[package]
name = "coc-rs"
version = "0.4.2"
authors = ["amaanq <amaanq12@gmail.com>", "SaHiL"]
edition = "2021"
description = "A Rust crate wrapper around the Clash of Clans public API"
readme = "README.md"
homepage = "https://github.com/amaanq/coc.rs"
repository = "https://github.com/amaanq/coc.rs"
license = "MIT"
license-file = "LICENSE"
keywords = ["Clash of Clans", "Clash", "coc", "api", "Supercell"]
categories = ["api-bindings", "asynchronous", "concurrency", "config", "web-programming::http-client"]
exclude = [".idea/", ".vscode/", "*.txt"]

[dependencies]
async-trait = "0.1.57"
base64 = "0.13.0"
chrono = "0.4.22"
lazy_static = "1.4.0"
logic-long = "0.1.1"
regex = "1"
time = "0.3.14"
urlencoding = "2.1.0"

serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
serde_repr = "0.1.9"

reqwest = { version = "0.11.10", features = ["json", "cookie_store", "cookies"] }
tokio = { version = "1.19.2", features = ["full"] }

[features]
default = []
cos = []
extra = []
all = ["cos", "extra"]