[package]
name = "coc-rs"
version = "0.7.5"
authors = ["Amaan Q <amaanq12@gmail.com>", "SaHiL"]
edition = "2021"
description = "A Rust crate wrapper around the Clash of Clans public API"
readme = "README.md"
homepage = "https://github.com/amaanq/coc.rs"
repository = "https://github.com/amaanq/coc.rs"
license = "MIT"
keywords = ["Clash_of_Clans", "Clash", "coc", "api", "Supercell"]
categories = ["api-bindings", "asynchronous", "concurrency", "config", "web-programming::http-client"]
exclude = [".idea/", ".vscode/", "*.txt"]

[dependencies]
anyhow = "1.0.66"
async-recursion = "1.0.0"
async-trait = "0.1.59"
base64 = "0.13.1"
chrono = "0.4.23"
dashmap = "5.4.0"
lazy_static = "1.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
regex = "1.7.0"
time = "0.3.17"
url = "2.3.1"
urlencoding = "2.1.2"

serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
serde_repr = "0.1.9"

futures = "0.3.25"
parking_lot = "0.12.1"
reqwest = { version = "0.11.13", features = ["json", "cookie_store", "cookies"] }
tokio = { version = "1.22.0", features = ["full"] }

tracing = { version = "0.1.37", optional = true }

[dev-dependencies]
rand = "0.8.5"

[lib]
doctest = false

[features]
default = []
cos = []
extra = []
all = ["cos", "extra", "tracing"]
