[package]
name = "coc-rs"
version = "0.3.3"
edition = "2021"
authors = ["amaanq", "SaHiL"]
description = "A Rust crate wrapper around the Clash of Clans public API"
license = "MIT"
homepage = "https://github.com/amaanq/coc.rs"
repository = "https://github.com/amaanq/coc.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
reqwest = { version = "0.11.10", features = ["json", "cookie_store", "cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
serde_repr = "0.1.9"
tokio = { version = "1.19.2", features = ["full"] }
chrono = "0.4.22"
urlencoding = "2.1.0"
bytestream-rs = "0.4.1"
time = "0.3.14"
base64 = "0.13.0"