[package]
name = "coc-rs"
version = "0.1.0"
edition = "2021"
authors = ["SaHiL"]
description = "A Rust library for Clash of clans API"
License = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
reqwest = { version = "0.11.10", features = ["json", "cookie_store", "cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["full"] }
