name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      max-parallel: 1
      matrix:
        profile:
          - debug
          - release
        include:
          - profile: release
            cargo_flags: "--release"
            cargo_env: ""
          - profile: debug
            cargo_flags: ""
            cargo_env: "RUSTFLAGS='-C debuginfo=0'"

    steps:
      - uses: actions/checkout@v3

      - name: Rust version
        id: rust-version
        run: |
          echo "::set-output name=rust_version::$(rustc --version)"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.profile }} ${{ runner.os }} ${{ steps.rust-version.outputs.rust_version }} ${{ hashFiles('Cargo.lock') }} ${{ hashFiles('src/**') }}
          restore-keys: |
            ${{ matrix.profile }} ${{ runner.os }} ${{ steps.rust-version.outputs.rust_version }} ${{ hashFiles('Cargo.lock') }}