name: Build

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Release Packaging
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Debug Build
        run: cargo build

      - name: Release Build
        run: cargo build --release
