name: Cargo Format

on: [push, pull_request]

jobs:
  cargofmt:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check
