name: Cargo Format

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on: [push, pull_request]

jobs:
  cargofmt:
    name: Check Rust formating
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo fmt -- --check
