on: 
  push:
    branches:
      - master
  pull_request:

name: clippy

jobs:
  clippy:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy -- -D warnings