name: Clippy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy -- -D warnings
